; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[common_env_data]
lib_extra_dirs = lib/Lightnet
build_flags =
    -Wno-reorder -Wno-switch
build_flags_controller =
    -D DEBUG=1
    -D LIGHTNET_TARGET_CONTROLLER
    -D DEMO_ENABLED=0
    -D BUFFER_LENGTH=256
    -D I2C_BUFFER_LENGTH=256
build_flags_panel =
    -D DEBUG=0
    -D TWI_BUFFER_SIZE=80

[env:controller_esp8266]
platform = espressif8266
board = esp12e
framework = arduino
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_controller}
upload_speed = 230400
lib_ldf_mode = chain+
upload_port = /dev/cu.wchusbserial1442420
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
lib_deps =
    ESPAsyncWifiManager
    ESP Async WebServer
    FastLED@3.3.2
lib_ignore = AsyncTCP_RP2040W

[env:controller_wemos]
platform = espressif8266
board = d1_mini_pro
framework = arduino
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_controller}
upload_speed = 460800
lib_ldf_mode = chain+
;upload_port = COM6
monitor_port = COM6
;monitor_port = usb
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
lib_deps =
    ESPAsyncWifiManager
    ESP Async WebServer
    FastLED@3.3.2
lib_ignore = AsyncTCP_RP2040W

monitor_speed = 57600

[env:controller_wemos_sim]
platform = espressif8266
board = d1_mini_pro
framework = arduino
upload_speed = 460800
monitor_port = COM6
monitor_speed = 230400
lib_ldf_mode = chain+
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
lib_deps =
    ESPAsyncWifiManager
    ESP Async WebServer
    FastLED@3.3.2
lib_ignore = AsyncTCP_RP2040W
build_flags =
    ${common_env_data.build_flags} ${common_env_data.build_flags_controller}
    -D SIM_MODE
    -D SIM_PANELS_COUNT=5
    -D SIM_SERIAL_BAUD=230400

[env:controller_esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_controller}
lib_ldf_mode = chain+
upload_speed = 460800
#upload_port = /dev/cu.usbserial-143110
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
lib_deps =
    ESPAsyncWifiManager
    ESP Async WebServer
    AnalogWrite
    FastLED@3.3.2
lib_ignore = AsyncTCP_RP2040W

[env:controller_wemos_s2]
platform = espressif32
board = lolin_s2_mini
; change microcontroller
board_build.mcu = esp32s2
; change MCU frequency
board_build.f_cpu = 240000000L
framework = arduino
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_controller}
lib_ldf_mode = chain+
upload_speed = 460800
#upload_port = /dev/cu.usbserial-143110
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
lib_deps =
    ESPAsyncWifiManager
    ESP Async WebServer
    AnalogWrite
    FastLED@3.3.2

[env:panel_atmega328p_via_controller]
platform = atmelavr
board = ATmega328P
framework = arduino
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_panel}
lib_ldf_mode = chain+
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
extra_scripts = post:tools/generate_bin.py
upload_protocol = custom
upload_port = COM6
upload_command = $PYTHONEXE "${PROJECT_DIR}/tools/flash_panels_serial.py" $UPLOAD_PORT "${BUILD_DIR}/firmware.bin"
lib_deps =
    FastLED@3.3.2
monitor_speed = 57600
monitor_port = COM18

[env:panel_atmega328pb]
platform = atmelavr
board = ATmega328PB
framework = arduino
board_fuses.lfuse = 0xF7
board_fuses.hfuse = 0xD8
board_fuses.efuse = 0xFC
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_panel}
lib_ldf_mode = chain+
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
extra_scripts = post:tools/generate_bin.py
; upload_port = COM9
; upload_protocol = arduino
upload_protocol = usbasp
upload_flags = -D
lib_deps =
    FastLED@3.3.2
monitor_speed = 57600
monitor_port =  COM18


[env:panel_atmega328p]
platform = atmelavr
board = ATmega328P
framework = arduino
board_fuses.lfuse = 0xF7
board_fuses.hfuse = 0xD8
board_fuses.efuse = 0xFC
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_panel}
lib_ldf_mode = chain+
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
extra_scripts = post:tools/generate_bin.py
; upload_port = COM9
; upload_protocol = arduino
upload_protocol = usbasp
upload_flags = -D
; upload_port=/dev/cu.usbmodem14424301
lib_deps =
    FastLED@3.3.2
monitor_speed = 57600
monitor_port =  COM18

[env:atmega328pb_bootloader]
platform = atmelavr
board = atmega328pb
board_fuses.lfuse = 0xF7
board_fuses.hfuse = 0xD8
board_fuses.efuse = 0xFC
upload_protocol = usbasp
build_src_filter = -<*> +<../twiboot/main.c>
extra_scripts = post:tools/generate_bin.py
build_flags =
    -DBOOTLOADER_START=0x7000
    -DTWI_ADDRESS=0x29
    -Dfalse=0
    -Dtrue=1
    -Os
    -Wno-cpp
    -fdata-sections
    -ffunction-sections
    -Wall
    -nostartfiles
    -Wl,--relax
    -Wl,--gc-sections
    -Wl,--section-start=.text=0x7000

[env:atmega328p_bootloader]
platform = atmelavr
board = atmega328p
board_fuses.lfuse = 0xF7
board_fuses.hfuse = 0xD8
board_fuses.efuse = 0xFC
upload_protocol = usbasp
build_src_filter = -<*> +<../twiboot/main.c>
extra_scripts = post:tools/generate_bin.py
build_flags =
    -DBOOTLOADER_START=0x7000
    -DTWI_ADDRESS=0x29
    -Dfalse=0
    -Dtrue=1
    -Os
    -Wno-cpp
    -fdata-sections
    -ffunction-sections
    -Wall
    -nostartfiles
    -Wl,--relax
    -Wl,--gc-sections
    -Wl,--section-start=.text=0x7000
