; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[common_env_data]
lib_extra_dirs = lib/Lightnet
build_flags = 
    -D DEBUG=1 -Wno-reorder -Wno-switch
build_flags_controller = 
    -D LIGHTNET_TARGET_CONTROLLER

[env:initializer_esp8266]
platform = espressif8266
board = esp12e
framework = arduino
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_controller}
upload_speed = 230400
lib_ldf_mode = chain+
upload_port = /dev/cu.wchusbserial1442420
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
lib_deps =
    ESPAsyncWifiManager
    ESP Async WebServer
    FastLED@3.3.2

[env:initializer_wemos]
platform = espressif8266
board = d1_mini
framework = arduino
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_controller}
upload_speed = 460800
lib_ldf_mode = chain+
upload_port = COM13
monitor_port = COM13
;monitor_port = usb
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
lib_deps =
    ESPAsyncWifiManager
    ESP Async WebServer
    FastLED@3.3.2

monitor_speed = 57600

[env:initializer_esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = ${common_env_data.build_flags} ${common_env_data.build_flags_controller}
lib_ldf_mode = chain+
upload_speed = 460800
#upload_port = /dev/cu.usbserial-143110
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
lib_deps =
    ESPAsyncWifiManager
    ESP Async WebServer
    AnalogWrite
    FastLED@3.3.2

[env:panel_nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = ${common_env_data.build_flags}
lib_ldf_mode = chain+
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
lib_deps = 
    FastLED@3.3.2

[env:panel_atmega328pb]
platform = atmelavr
board = ATmega328PB
framework = arduino
build_flags = ${common_env_data.build_flags}
lib_ldf_mode = chain+
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
upload_protocol = usbasp
;upload_port = COM14
lib_deps = 
    FastLED@3.3.2
monitor_speed = 57600
monitor_port = COM15
upload_speed = 19200


[env:panel_atmega328p]
platform = atmelavr
board = ATmega328P
framework = arduino
build_flags = ${common_env_data.build_flags}
lib_ldf_mode = chain+
lib_extra_dirs = ${common_env_data.lib_extra_dirs}
upload_protocol = usbasp
;upload_protocol = avrisp
; upload_port=/dev/cu.usbmodem14424301
lib_deps = 
    FastLED@3.3.2
monitor_speed = 57600
monitor_port =  COM13