; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
lib_extra_dirs =
    ../lib/Lightnet
    ../lib

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -D DEBUG=1
lib_ldf_mode = chain+
upload_port = /dev/cu.SLAB_USBtoUART
lib_deps =
    Wire
    ESP32 AnalogWrite

[env:esp8266]
platform = espressif8266
board = esp07
framework = arduino
build_flags = -D DEBUG=1
upload_speed = 921600
lib_ldf_mode = chain+
upload_port = /dev/cu.usbserial-141130

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = -D DEBUG=1
lib_ldf_mode = chain+
lib_deps =
    Wire
