; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html
[platformio]
lib_extra_dirs =
    ../lib/Lightnet
    ../lib

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_port = COM6
build_flags = -D DEBUG=1

[env:nanoatmega168]
platform = atmelavr
board = nanoatmega168
framework = arduino
upload_port = COM5

[env:due]
platform = atmelsam
board = due
framework = arduino
