; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html
[platformio]
lib_extra_dirs =
    ../lib/Lightnet
    ../lib

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = -D DEBUG=1
lib_ldf_mode = chain+
lib_deps =
    Wire

[env:nanoatmega328_1]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = -D DEBUG=1
lib_ldf_mode = chain+
upload_port = /dev/cu.usbserial-1411430
lib_deps =
    Wire

[env:nanoatmega328_2]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = -D DEBUG=1
lib_ldf_mode = chain+
upload_port = /dev/cu.usbserial-1411440
lib_deps =
    Wire

[env:nanoatmega168]
platform = atmelavr
board = nanoatmega168
framework = arduino
build_flags = -D DEBUG=1
lib_ldf_mode = chain+
lib_deps =
    Wire

[env:due]
platform = atmelsam
board = due
framework = arduino
build_flags = -D DEBUG=1
lib_ldf_mode = chain+
lib_deps =
    Wire

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -D DEBUG=1
lib_ldf_mode = chain+
lib_deps =
    Wire
