; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[common_env_data]
lib_extra_dirs =
    ../lightnet/lib

[env:miniatmega328]
platform = atmelavr
board = miniatmega328
framework = arduino
lib_extra_dirs =
    ${common_env_data.lib_extra_dirs}

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_extra_dirs =
    ${common_env_data.lib_extra_dirs}

[env:nanoatmega168]
platform = atmelavr
board = nanoatmega168
framework = arduino
lib_extra_dirs =
    ${common_env_data.lib_extra_dirs}

[env:due]
platform = atmelsam
board = due
framework = arduino
upload_port = COM7
lib_extra_dirs =
    ${common_env_data.lib_extra_dirs}
